<a href="https://colab.research.google.com/github/ashugk/365datadcience/blob/main/homework01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

What's the version of Pandas that you installed?

In [ ]:
import pandas as pd
pd.__version__

'1.5.3'

Load the data and read it in pandas

In [ ]:
dataset= pd.read_csv('housing.csv')

Question 2

How many columns are in the dataset?

In [ ]:
dataset.info()#total 10 columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


Question 3

Which columns in the dataset have missing values?

In [ ]:
# create a Boolean mask for missing values
missing_values = dataset.isnull()

# count the number of missing values in each column
missing_counts = missing_values.sum()

# print the column names with missing values
print(missing_counts[missing_counts > 0].index.tolist())

['total_bedrooms']


Question 4

How many unique values does the ocean_proximity column have?

In [ ]:
unique_values=dataset['ocean_proximity'].unique()
unique_count= len(unique_values)
print(unique_count)

5


Question 5

What's the average value of the median_house_value for the houses located near the bay?

    49433
    124805
    259212
    380440


In [16]:
# Filter the DataFrame for houses located near the bay
near_bay_df = dataset[dataset['ocean_proximity'] == 'NEAR BAY']

# Calculate the average value of median_house_value for houses near the bay
average_median_house_value_near_bay = near_bay_df['median_house_value'].mean()

print("Average median house value for houses near the bay:", average_median_house_value_near_bay)

Average median house value for houses near the bay: 259212.31179039303


Question 6

    Calculate the average of total_bedrooms column in the dataset.
    Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
    Now, calculate the average of total_bedrooms again.
    Has it changed?


Has it changed?

    Hint: take into account only 3 digits after the decimal point.

    Yes
    No


In [19]:
# Calculate the average of the total_bedrooms column
average_total_bedrooms_before_fillna = dataset['total_bedrooms'].mean()

print("Average total bedrooms before fillna:", average_total_bedrooms_before_fillna)

Average total bedrooms before fillna: 537.8705525375618


In [21]:
# Fill missing values in the total_bedrooms column with the mean value
dataset['total_bedrooms'].fillna(average_total_bedrooms_before_fillna, inplace=True)

In [23]:
# Calculate the average of the total_bedrooms column after filling missing values
average_total_bedrooms_after_fillna = dataset['total_bedrooms'].mean()

print("Average total bedrooms after fillna:", average_total_bedrooms_after_fillna)

Average total bedrooms after fillna: 537.8705525375617


In [24]:
#Ans No change

Q7.1 Select all the options located on islands

In [25]:
# Select rows where the 'ocean_proximity' column is 'ISLAND'
island_properties = dataset[dataset['ocean_proximity'] == 'ISLAND']

Q7.2Select only columns housing_median_age, total_rooms, total_bedrooms.

In [26]:
# Select specific columns
selected_columns = dataset[['housing_median_age', 'total_rooms', 'total_bedrooms']]

Q7.3 Get the underlying NumPy array. Let's call it X

In [29]:
# Get the underlying NumPy array
X = dataset[['housing_median_age', 'total_rooms', 'total_bedrooms']].values
X

array([[  41.,  880.,  129.],
       [  21., 7099., 1106.],
       [  52., 1467.,  190.],
       ...,
       [  17., 2254.,  485.],
       [  18., 1860.,  409.],
       [  16., 2785.,  616.]])

Q 7.4  Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [31]:
# Compute the matrix-matrix multiplication
import numpy as np
XTX = np.dot(X.T, X)
XTX

array([[2.01984850e+07, 1.35332892e+09, 2.83204712e+08],
       [1.35332892e+09, 2.41621366e+11, 4.67660348e+10],
       [2.83204712e+08, 4.67660348e+10, 9.59926544e+09]])

Q 7.5 Compute the inverse of XTX.

In [32]:
# Compute the inverse of XTX
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 8.47988169e-08,  1.62386103e-10, -3.29291640e-09],
       [ 1.62386103e-10,  7.28537219e-11, -3.59722129e-10],
       [-3.29291640e-09, -3.59722129e-10,  1.95383149e-09]])

Q 7.6 Create an array y with values [950, 1300, 800, 1000, 1300].

In [34]:
# Create the array 'y'
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

Q 7.7 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [35]:
# Compute the result 'w'
w = np.dot(np.dot(inv_XTX, X.T), y)
w

ValueError: ignored