<a href="https://colab.research.google.com/github/ashugk/365datadcience/blob/main/homework01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

What's the version of Pandas that you installed?

In [1]:
import pandas as pd
pd.__version__

'1.5.3'

Load the data and read it in pandas

In [2]:
dataset= pd.read_csv('housing.csv')

Question 2

How many columns are in the dataset?

In [3]:
dataset.info()#total 10 columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


Question 3

Which columns in the dataset have missing values?

In [4]:
# create a Boolean mask for missing values
missing_values = dataset.isnull()

# count the number of missing values in each column
missing_counts = missing_values.sum()

# print the column names with missing values
print(missing_counts[missing_counts > 0].index.tolist())

['total_bedrooms']


Question 4

How many unique values does the ocean_proximity column have?

In [5]:
unique_values=dataset['ocean_proximity'].unique()
unique_count= len(unique_values)
print(unique_count)

5


Question 5

What's the average value of the median_house_value for the houses located near the bay?

    49433
    124805
    259212
    380440


In [6]:
# Filter the DataFrame for houses located near the bay
near_bay_df = dataset[dataset['ocean_proximity'] == 'NEAR BAY']

# Calculate the average value of median_house_value for houses near the bay
average_median_house_value_near_bay = near_bay_df['median_house_value'].mean()

print("Average median house value for houses near the bay:", average_median_house_value_near_bay)

Average median house value for houses near the bay: 259212.31179039303


Question 6

    Calculate the average of total_bedrooms column in the dataset.
    Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
    Now, calculate the average of total_bedrooms again.
    Has it changed?


Has it changed?

    Hint: take into account only 3 digits after the decimal point.

    Yes
    No


In [7]:
# Calculate the average of the total_bedrooms column
average_total_bedrooms_before_fillna = dataset['total_bedrooms'].mean().round(3)

print("Average total bedrooms before fillna:", average_total_bedrooms_before_fillna)

Average total bedrooms before fillna: 537.871


In [8]:
# Fill missing values in the total_bedrooms column with the mean value
dataset['total_bedrooms'].fillna(average_total_bedrooms_before_fillna, inplace=True)

In [9]:
# Calculate the average of the total_bedrooms column after filling missing values
average_total_bedrooms_after_fillna = dataset['total_bedrooms'].mean().round(3)

print("Average total bedrooms after fillna:", average_total_bedrooms_after_fillna)

Average total bedrooms after fillna: 537.871


In [10]:
#Ans No change

Q7.1 Select all the options located on islands

In [18]:
# Select rows where the 'ocean_proximity' column is 'ISLAND'
island_properties = dataset[dataset['ocean_proximity'] == 'ISLAND']
island_properties.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

Q7.2Select only columns housing_median_age, total_rooms, total_bedrooms.

In [19]:
# Select specific columns
selected_columns = island_properties[['housing_median_age', 'total_rooms', 'total_bedrooms']]
print(selected_columns)

      housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0


Q7.3 Get the underlying NumPy array. Let's call it X

In [20]:
# Get the underlying NumPy array
X = selected_columns.values
print(X)

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


Q 7.4  Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [21]:
# Compute the matrix-matrix multiplication
import numpy as np
# Compute the transpose of X
X_transpose = X.T
# Compute XTX (matrix-matrix multiplication)
XTX = np.dot(X_transpose, X)
print(XTX)

[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


Q 7.5 Compute the inverse of XTX.

In [22]:
# Compute the inverse of XTX
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

Q 7.6 Create an array y with values [950, 1300, 800, 1000, 1300].

In [23]:
# Create the array 'y'
y = np.array([950, 1300, 800, 1000, 1300])
y.shape

(5,)

Q 7.7 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [26]:
# Compute the result 'w'
# Calculate the inverse of XTX
XTX_inverse = np.linalg.inv(XTX)
#print(XTX_inverse.shape)
# Transpose 'y' to make it a row vector (shape: (1,5))
y_transpose = y.T
# Calculate w by multiplying the inverse of XTX with the transpose of X, and then multiplying by y
#w = np.dot(np.dot(XTX_inverse, X_transpose), y)
# Calculate w by multiplying the inverse of XTX with the transpose of X, and then multiplying by the transposed 'y'
w = np.dot(np.dot(XTX_inverse, X_transpose), y_transpose)
print(w)

[23.12330961 -1.48124183  5.69922946]


In [27]:
#Ans : 5.6992