<a href="https://colab.research.google.com/github/ashugk/365datadcience/blob/main/MultipleLinearRegressionUsingSKLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [2]:
data= pd.read_csv('Multiple_linear_regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [4]:
x=data[['SAT', 'Rand 1,2,3']]
y= data['GPA']

In [5]:
reg= LinearRegression()
reg.fit(x,y)

LinearRegression()

In [11]:
reg.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909486

<h1>Calulcating the R-squared </h1>

In [8]:
reg.score(x,y)

0.4066811952814283

### Formula for adjusted-R^2

$R^2_{adj.}= 1- (1- R^2)*\frac{n-1}{n-p-1}$

In [12]:
x.shape

(84, 2)

In [14]:
r2 = reg.score(x,y)

n = x.shape[0] #(no of observations=84)
p = x.shape[1] #(no of features= 2)

adjusted_r2=  1-(1- r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

##Feature Selection

In [18]:
from sklearn.feature_selection import f_regression

f_regression(x,y)
# gives f-stat and p_value as output

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [16]:
p_value= f_regression(x,y)[1]
p_value

array([7.19951844e-11, 6.76291372e-01])

rounding to 3 digit. we see p_value < 0.05 to reject a feature. So featue rand1,2,3 is rejected while SAT is kept as a feature.

In [17]:
p_value.round(3)

array([0.   , 0.676])